<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJofhze5\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJofhze5/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJofhze5.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerJofhze5\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerJofhze5\appProdProjectContainer([
    'container.build_hash' => 'Jofhze5',
    'container.build_id' => '595a3f1a',
    'container.build_time' => 1570797153,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJofhze5');
